### ISSUE TITLE
support 'Gitea' 's  (and its fokr : Forgejo ?)  server ?

### ISSUE THREAD

**Issue by fenix011** [sshaw/git-link#117]
Hi
  I run my own git ( ['Gitea' server](https://gitea.com/) ) ... which is becoming a more and more popular 'self-hosted' option !
that would be great to enjoy git-link there too

thX thX thX

**Comment by sshaw** [comment]
Yes sounds good. What is the format of the URLs that must be generated?

**Comment by port19x** [comment]
It's very similar to github, but instead of blob it needs either `src/branch` or `src/commit`.
This could be a default entry in the alist, since gitea is meant to be selfhosted and thus has all sorts of urls.

`git-link-commit` and `git-link-homepage` work as-is with the respective github backends

**Comment by port19x** [comment]
gitea works with codebergs `git-link` backend

**Comment by sshaw** [comment]
As discussed in #126 Gitea is supported in the same way we support cgit: user has to explicitly configure their self-hosted URL. No need to try to provide a default that acts as the default matching rule due to its loose syntax. 

See the [cgit and Gitea section](https://github.com/sshaw/git-link?tab=readme-ov-file#cgit-and-gitea) in the README.
